# Generated by Django 5.0.1 on 2024-01-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('ku', 'Kurti'), ('bl', 'bluetooth'), ('so', 'shoes'), ('wa', 'watch')], max_length=2),
        ),
    ]
